# Generated by Django 4.2.28 on 2026-02-08 19:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('warning', 'Warning'), ('info', 'Information'), ('success', 'Success'), ('prediction', 'Prediction'), ('recommendation', 'Recommendation')], max_length=20)),
                ('category', models.CharField(choices=[('attendance_pattern', 'Attendance Pattern'), ('risk_assessment', 'Risk Assessment'), ('trend_analysis', 'Trend Analysis'), ('performance_prediction', 'Performance Prediction'), ('course_analysis', 'Course Analysis'), ('student_behavior', 'Student Behavior')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('confidence_score', models.FloatField(default=0)),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('recommendations', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_actionable', models.BooleanField(default=True)),
                ('analysis_period_start', models.DateField(blank=True, null=True)),
                ('analysis_period_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AI Insight',
                'verbose_name_plural': 'AI Insights',
                'db_table': 'ai_insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('daily', 'Daily Report'), ('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('semester', 'Semester Report'), ('custom', 'Custom Period Report')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('summary', models.JSONField(blank=True, null=True)),
                ('detailed_data', models.JSONField(blank=True, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('file_format', models.CharField(default='pdf', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attendance Report',
                'verbose_name_plural': 'Attendance Reports',
                'db_table': 'attendance_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('granularity', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('date', models.DateField()),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_students_expected', models.IntegerField(default=0)),
                ('total_present', models.IntegerField(default=0)),
                ('total_late', models.IntegerField(default=0)),
                ('total_absent', models.IntegerField(default=0)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attendance Trend',
                'verbose_name_plural': 'Attendance Trends',
                'db_table': 'attendance_trends',
                'ordering': ['-date'],
            },
        ),
    ]
