# Generated by Django 4.2.28 on 2026-02-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIInsight',
        ),
    ]
