# Generated by Django 4.2.28 on 2026-02-08 19:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('excused', 'Excused')], default='absent', max_length=20)),
                ('verification_method', models.CharField(choices=[('fingerprint', 'Fingerprint'), ('manual', 'Manual'), ('qr_code', 'QR Code'), ('facial', 'Facial Recognition')], default='manual', max_length=20)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('verification_confidence', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('excuse_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('session_type', models.CharField(choices=[('lecture', 'Lecture'), ('tutorial', 'Tutorial'), ('lab', 'Laboratory'), ('seminar', 'Seminar'), ('exam', 'Examination')], default='lecture', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('allow_late_marking', models.BooleanField(default=True)),
                ('late_threshold_minutes', models.IntegerField(default=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'db_table': 'attendance_sessions',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_sessions', models.IntegerField(default=0)),
                ('present_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('absent_count', models.IntegerField(default=0)),
                ('excused_count', models.IntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Summary',
                'verbose_name_plural': 'Attendance Summaries',
                'db_table': 'attendance_summaries',
            },
        ),
    ]
