# Generated by Django 4.2.28 on 2026-03-03 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_academicyear_course_semester_number_and_more'),
        ('attendance', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='timetable_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='courses.timetableslot'),
        ),
    ]
