# Generated by Django 4.2.28 on 2026-03-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_time',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('evening', 'Evening'), ('weekend', 'Weekend')], max_length=10, null=True),
        ),
    ]
