# Generated by Django 4.2.28 on 2026-03-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_add_lecturer_to_timetable_slot'),
        ('users', '0003_add_study_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='courses.academicyear'),
        ),
    ]
