# Generated by Django 4.2.28 on 2026-03-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_academicyear_course_semester_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='study_time',
            field=models.CharField(choices=[('day', 'Day'), ('evening', 'Evening'), ('weekend', 'Weekend')], default='day', max_length=10),
        ),
    ]
