# Generated by Django 4.2.28 on 2026-03-20 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_add_lecturer_to_timetable_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coordinator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
