# Generated by Django 4.2.28 on 2026-03-20 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_course_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='student_coordinator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_cohorts_as_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
