# Generated by Django 4.2.28 on 2026-03-31 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0008_cohort_student_coordinator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='student_coordinator',
        ),
        migrations.CreateModel(
            name='CohortGroupCoordinator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_time', models.CharField(choices=[('day', 'Day'), ('evening', 'Evening'), ('weekend', 'Weekend')], max_length=10)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_coordinators', to='courses.cohort')),
                ('coordinator', models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cohort_group_coordinators',
                'unique_together': {('cohort', 'study_time')},
            },
        ),
    ]
